name: panepond
description: A simple *panepon/panel de pon/tetris attack/crack attack* clone
dependencies:
  polymer: '>=0.14.0 <0.15.0'
  core_elements: any
  browser: any
  range:
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    commandLineOptions: ["--enable-enum"]
